plugins {
    id 'com.android.application'
}

android {
    compileSdk 28

    defaultConfig {
        applicationId 'com.screenvideo.free'
        minSdk 9
        targetSdk 22
        versionCode 1
        versionName '0.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
}
